export const FL_ASSETS_LAND = 'FL_ASSETS_LAND';
export const FL_ASSETS_BUILDINGS = 'FL_ASSETS_BUILDINGS';
export const FL_ASSETS_EQUIPMENT = 'FL_ASSETS_EQUIPMENT';
export const FL_ASSETS_TRANSPORT = 'FL_ASSETS_TRANSPORT';
export const FL_ASSETS_INTANGIBLE = 'FL_ASSETS_INTANGIBLE';
export const FL_ASSETS_OTHERS = 'FL_ASSETS_OTHERS';
// export const FL_ASSETS_CASH = 'FL_ASSETS_CASH';
export const FL_ASSETS_TOTAL = 'FL_ASSETS_TOTAL';

export const FL_INVEST_LAND = 'FL_INVEST_LAND';
export const FL_INVEST_BUILDINGS = 'FL_INVEST_BUILDINGS';
export const FL_INVEST_EQUIPMENT = 'FL_INVEST_EQUIPMENT';
export const FL_INVEST_TRANSPORT = 'FL_INVEST_TRANSPORT';
export const FL_INVEST_INTANGIBLE = 'FL_INVEST_INTANGIBLE';
export const FL_INVEST_OTHERS = 'FL_INVEST_OTHERS';
export const FL_INVEST_TOTAL = 'FL_INVEST_TOTAL';

export const FL_INVESTMENTS_ALL = 'FL_INVESTMENTS_ALL';
export const FL_INVESTMENTS_ALREADY_INVESTED = 'FL_INVESTMENTS_ALREADY_INVESTED';
export const FL_INVESTMENTS_OWN_CASH = 'FL_INVESTMENTS_OWN_CASH';
export const FL_INVESTMENTS_OWN_ALL = 'FL_INVESTMENTS_OWN_ALL';
export const FL_INVESTMENTS_TO_BORROW = 'FL_INVESTMENTS_TO_BORROW';
export const FL_INVESTMENTS_RATIO = 'FL_INVESTMENTS_RATIO';
export const FL_INVESTMENTS_LOAN_RATE = 'FL_INVESTMENTS_LOAN_RATE';


export const FL_CALC001 = {
    FL_AVERAGE_AMOUNT : 'FL_CALC001_AVERAGE_AMOUNT',
    FL_CUSTOMER_NUMBER_PER_MONTH : 'FL_CALC001_CUSTOMER_NUMBER',
}

export const FL_INCOME_AVERAGE_PRICE = 'FL_INCOME_AVERAGE_PRICE';
export const FL_INCOME_AVERAGE_SALES_PER_DAY = 'FL_INCOME_AVERAGE_SALES_PER_DAY';
export const FL_INCOME_PER_MONTH = 'FL_INCOME_PER_MONTH';
export const FL_INCOME_TOTAL = 'FL_INCOME_TOTAL';

// export const FL_EXPENSES_TAXES = 'FL_EXPENSES_TAXES';
// export const FL_EXPENSES_GROSS_MARGIN = 'FL_EXPENSES_GROSS_MARGIN';
// export const FL_EXPENSES_NET_MARGIN = 'FL_EXPENSES_NET_MARGIN';
export const FL_EXPENSES_IS_MANUAL = 'FL_EXPENSES_IS_MANUAL';
export const FL_EXPENSES_MANUAL = {
    FL_MANAGEMENT_COUNT : 'FL_EXPENSES_M_MANAGEMENT_COUNT',
    FL_MANAGEMENT_SALARY : 'FL_EXPENSES_M_MANAGEMENT_SALARY',
    FL_EMPLOYEE_COUNT : 'FL_EXPENSES_M_EMPLOYEE_COUNT',
    FL_EMPLOYEE_SALARY : 'FL_EXPENSES_M_EMPLOYEE_SALARY',
    FL_RENT : 'FL_EXPENSES_M_RENT',
    FL_TRANSPORT : 'FL_EXPENSES_M_TRANSPORT',
    FL_TAXES : 'FL_EXPENSES_M_TAXES',
    FL_OTHERS : 'FL_EXPENSES_M_OTHERS',
}
export const FL_EXPENSES_TOTAL = 'FL_EXPENSES_TOTAL';

export const FL_PARAMS_GROSS_MARGIN = 'FL_PARAMS_GROSS_MARGIN';
export const FL_PARAMS_NET_MARGIN = 'FL_PARAMS_NET_MARGIN';
// export const FL_INVESTMENTS_LOAN_RATE = 'FL_INVESTMENTS_LOAN_RATE';
export const FL_PARAMS_DIVIDENTS = 'FL_PARAMS_DIVIDENTS';


export const FLTYPE_AMOUNT = 1;
export const FLTYPE_NUMBER = 2;
export const FLTYPE_STRING = 3;
