// export const SET_MODEL_INITIAL = 'SET_MODEL_INITIAL';
// export const GET_MODEL_INPUT2_SUCCESS = 'GET_MODEL_INPUT2_SUCCESS';
export const UPDATE_FIELD = 'UPDATE_FIELD';
export const COPY_BIGDATA_TO_FIELDS = 'COPY_BIGDATA_TO_FIELDS';

// export const modelActions = [SET_MODEL_INITIAL, GET_MODEL_INPUT2_SUCCESS, UPDATE_FIELD];
export const modelActions = [UPDATE_FIELD, COPY_BIGDATA_TO_FIELDS];
